stages:
  - build
  - deploy
  - verifysanity
  - verify

variables:
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
  GIT_SUBMODULE_STRATEGY: normal

internal:
  tags:
    - ios_internal
  stage: build
  only:
    - master
  except:
    - tags
  script:
    - bash buildbox/build-telegram.sh hockeyapp
    - bash buildbox/deploy-telegram.sh hockeyapp
  environment:
    name: internal
  artifacts:
    when: always
    paths:
      - build/artifacts
    expire_in: 1 week

appstore_development:
  tags:
    - ios_internal
  stage: build
  only:
    - appstore-development
  except:
    - tags
  script:
    - bash buildbox/build-telegram.sh appstore-development
    - bash buildbox/deploy-telegram.sh appstore-development
  environment:
    name: appstore-development
  artifacts:
    paths:
      - build/artifacts/Telegram.DSYMs.zip
    expire_in: 1 week

experimental_i:
  tags:
    - ios_experimental
  stage: build
  only:
    - experimental-3
  except:
    - tags
  script:
    - PYTHONPATH="$PYTHONPATH:/darwin-containers" python3 build-system/Make/Make.py remote-build --darwinContainersHost="http://host.docker.internal:8650" --cacheHost="grpc://host.docker.internal:9092" --configurationPath=build-system/appstore-configuration.json  --gitCodesigningRepository="$TELEGRAM_GIT_CODESIGNING_REPOSITORY" --gitCodesigningType=appstore --configuration=release_arm64
  environment:
    name: experimental
  artifacts:
    paths:
      - build/artifacts/Telegram.DSYMs.zip
    expire_in: 1 week

experimental:
  tags:
    - ios_internal
  stage: build
  only:
    - experimental-2
  except:
    - tags
  script:
    - bash buildbox/build-telegram.sh appcenter-experimental-2
    - bash buildbox/deploy-telegram.sh appcenter-experimental-2
  environment:
    name: experimental-2
  artifacts:
    paths:
      - build/artifacts/Telegram.DSYMs.zip
    expire_in: 1 week

beta_testflight:
  tags:
    - ios_beta
  stage: build
  only:
    - beta
    - hotfix
  except:
    - tags
  script:
    - bash buildbox/build-telegram.sh appstore
  environment:
    name: testflight_llc
  artifacts:
    paths:
      - build/artifacts
    expire_in: 3 weeks

deploy_beta_testflight:
  tags:
    - ios_beta
  stage: deploy
  only:
    - beta
    - hotfix
  except:
    - tags
  script:
    - bash buildbox/deploy-telegram.sh appstore
  environment:
    name: testflight_llc

verifysanity_beta_testflight:
  tags:
    - ios_beta
  stage: verifysanity
  only:
    - beta
    - hotfix
  except:
    - tags
  script:
    - bash buildbox/verify-telegram.sh appstore cached
  environment:
    name: testflight_llc
  artifacts:
    when: on_failure
    paths:
      - build/artifacts
    expire_in: 1 week

verify_beta_testflight:
  tags:
    - ios_beta
  stage: verify
  only:
    - beta
    - hotfix
  except:
    - tags
  script:
    - bash buildbox/verify-telegram.sh appstore full
  environment:
    name: testflight_llc
  artifacts:
    when: on_failure
    paths:
      - build/artifacts
    expire_in: 1 week
